version: '2'
services:
    kukulkan-app:
        image: kukulkan
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kukulkan-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=kukulkan
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kukulkan-mongodb:
        extends:
            file: mongodb.yml
            service: kukulkan-mongodb
